config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  get '/index', to: 'pnl#index'
  get 'pnl/show'
  get 'pnl/new'
  get '/about', to: 'pnl#about'
  get '/contact', to: 'pnl#contact'
 
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_one_attached :image
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50}
  validates :area, presence: true, length: { maximum: 50}
  validates :name, presence: true, length: { maximum: 50}
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "投稿できるのは .jpeg .gif .pngになります。"},
                            size: { less_than: 5.megabytes,
                                    message: "投稿できるのは、5MBまでになります。"}
  validates :content, presence: true, length: { maximum: 2000}
  
  has_rich_text :content


  def display_image
    image.variant(resize_to_limit: [500,500])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        posts_path
    end
    
    private

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        end
end

app/controllers/pnl_controller.rb
class PnlController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.image.attach(params[:post][:image])
    @post.user_id = current_user.id
    @post.save
    redirect_to post_path(@post)
    flash[:info] = "投稿が完了しました"
  end

  def edit
  end

  private
    def post_params
      params.require(:post).permit(:title, :area, :name, :image, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pnl_helper.rb
module PnlHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer>
    <div class="pnl-logo">
        <a href="https://www.personal.co.jp/" target="_blank">
        <%= image_pack_tag 'media/images/pnl-logo.png' %>
        </a>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="header-area">
        <div class="header-logo">
            <%= link_to root_path do %>
                <%= image_pack_tag 'media/images/logo.png' %>
            <% end %>
        </div>
        <div class="header-list">
            <ul class="header-center">
                <% if user_signed_in? %>
                    <li><%= link_to "使い方", about_path %></li>
                    <li><%= link_to "検索する", about_path %></li>
                    <li><%= link_to "お問い合わせ", contact_path %></li>
                    <li><%= link_to "投稿する", new_post_path %></li>
                <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
        <div class="header-right">
            <ul class="header-right-list">
                <% if user_signed_in? %>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                <% else %>
                <% end %>
            </ul>
                
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PnlApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="main-contents">
    <!-- flash-->
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>  
      
    
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pnl/about.html.erb
<h1>Pnl#about</h1>
<p>Find me in app/views/pnl/about.html.erb</p>

app/views/pnl/contact.html.erb
<h1>お問い合わせ</h1>
<p>Find me in app/views/pnl/destroy.html.erb</p>

app/views/pnl/destroy.html.erb
<h1>Pnl#destroy</h1>
<p>Find me in app/views/pnl/destroy.html.erb</p>

app/views/pnl/index.html.erb
<h1>Pnl#index</h1>
<p>Find me in app/views/pnl/index.html.erb</p>

app/views/pnl/new.html.erb
<h1>Pnl#new</h1>
<p>Find me in app/views/pnl/new.html.erb</p>

app/views/pnl/show.html.erb
<h1>Pnl#show</h1>
<p>Find me in app/views/pnl/show.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="index-title">
    <h1>社員通用口一覧</h1>
    <p>Find me in app/views/posts/index.html.erb</p>
</div>
    
<div class="index-area">
    <% @posts.each do |post| %>
        <%= link_to post_path(post) do %>
        <div class="index-card">
            <div class="index-image">
                <%= image_tag post.display_image if post.image.attached? %>
            </div>
            <div class="index-dsc">
                <%= post.title.truncate(20) %>
            </div>
        </div>
        <% end %>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="input-area">
    <div class="input-title">
        <h1>入力ページ</h1>
        <p>社員通用口の入力ページになります。</p>
    </div>

    <%= form_with(model: @post, local: true) do |f| %>
    <div class="input-content">
        
        <div class="input-item">
            <div class="input-label"><%= f.label :title, "タイトル" %></div>
            <div class="input-form"><%= f.text_field :title, placeholder: "タイトル" %></div>
        </div>
        
        <div class="input-item">
            <div class="input-label"><%= f.label :area, "エリア" %></div>
            <div class="input-form"><%= f.text_field :area, placeholder: "施設所在地" %></div>
        </div>
        
        <div class="input-item">
            <div class="input-label"><%= f.label :name, "施設名" %></div>
            <div class="input-form"><%= f.text_field :name, placeholder: "施設名" %></div>
        </div>
        
        <div class="input-item">
            <div class="input-label"><%= f.label :image, "トップ画像" %></div>
            <div class="input-form"><%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %></div>
        </div>
        
        <div class="input-rich">
            <div class="input-rich-label"><%= f.label :content, "テキストエリア" %></div>
            <div class="input-rich-form"><%= f.rich_text_area :content, placeholder: "従業員口を書いてください" %></div>
        </div>
        
        <div class="input-btn">
            <%= f.submit "投稿する", class:"input-buttom" %>
        </div>
    <% end %>
    </div>  
</div>

app/views/posts/show.html.erb
<div class="post-show">
    <div class="post-show-title">
        <h1><%= @post.title %>の社員通用口</h1>
    </div>
    
    <div class="post-top-image">
        <%= image_tag @post.display_image if @post.image.attached? %>
    </div>
    
    
    
    <%= @post.area %>
    
    <%= @post.name %>
    
    <%= @post.content %>
    
    <% if @post.user.id == current_user.id %>
        <%= link_to "編集する", edit_post_path(@post) %>
    <% end %>
    
    <p>投稿者: <%= @post.user.name %></p>
    
    
    
</div>